services:
- docker
script:
- make
- ls -la | grep pdf
deploy:
  provider: releases
  api_key:
    secure: a/Mu0RROgmwCby3jfC7IKVDcz/Rq3HnaLRFdf0sO7fSzIcmW5FWjESpybOmYs6ctlkwRFAJQzHYBgELbeLSAzsD49jBnZPEGQNUVK/33h4qu1L7OJ7MX+aGx/z63DSOBkPbK69YV3yHOs0HnRBdxV60B73NlZDo+gQcDiRDzeSmJgelnz99yEMyACNM7LwmMFg6kLmAdZUPax7eri6d5WNEN2PFFyDw3myT7MQnWjZuHue+Rxq9wJAJHx1HglxdLY7wKEPkj01nlYqloZBN22KGFq1hlJmiX/4JLELiPd18bKc5Qf3smkGFtCOBpHH6gBgegTJB932sG1fDlETYUDgfCBctjxPqLQsNmQYUO7C1vpN1mqm4KKUWc+87FtY3UAB7eTtferl9M9teHEj9Y+fvAwwHuhvlnqOCYkEXxLqlzcWGKDharUBE0dxvmWJ7rqoAC0tyAvhwVGNze0gyKYUyiyVs7OuuDFJqhlr4mRo0dfWcT4yUjHy8shOAvD+lQ9ZK3woCbFJxsoyNgXKTRKJIGoNujlkyjs7lf07lgD1duBQ7+zoHCYNRvYVYb6/jq0uuowegTMwmUQQeK554RogkLiHf8C0wItx/IjfEi0TrdRD69SpvyYXlcCvvQC8rAnik2sP/2HwU/wD2TvtZ9oB3aBJupVTcrm9auPaZitqo=
  file: seminar.pdf
  skip_cleanup: true
  on:
    repo: uniba-ktr/SemiTeX
    tags: true
